### ISSUE TITLE
af::freeHost(data) can cause problems

### ISSUE THREAD

**Issue by stupel** [pavolmarak/AF2MAT-MAT2AF#1]
I found a problem in function 
`cv::Mat Converter::af2mat(const af::array &input);`

If there is
`af::freeHost(data);`
I get wrong Mat output after first conversion, from second the result is good, but if I delete this line the result is each time good.

![array2mat](https://user-images.githubusercontent.com/15365632/38858856-11a14eb4-422d-11e8-9057-470559b1f047.png)

**Comment by pavolmarak** [comment]
Solved. Deep copy of returned ArrayFire data had to be done before releasing memory.
